<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/31
 * Time: 15:11
 */

namespace app\index\controller;


use rongyun\api\RongCloud;
use think\Controller;
use think\Db;

class Base extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign([
            'API' => config('api_domain'),
        ]);
        $company = Db::name('explain')->field('content')->where('id',4)->find();
        $addr = Db::name('explain')->field('content')->where('id',5)->find();
        $this->assign([
            'company'=>$company['content'],
            'addr'=>$addr['content']
        ]);
    }
    protected function R_token(){
            $model = new RongCloud(config('rongyun')['appKey'],config('rongyun')['appSecret']);
            $role_id = "xs_".time().rand(1,999);
            $header_img = config('default_img') ? config('default_img'):'x.png';
            $result = $model->user()->getToken($role_id,'游客'.$role_id,$header_img);
            $res = json_decode($result,true);
            if ($res['code'] == 200){
                return $res['token'];
            }else{
                return false;
            }
    }

    protected function getPlayInfo($id){
        $playInfo = cache('playUrlCache'.$id);
        if ($playInfo){
            return $playInfo;
        }else{
            $snapshotDomain = config('qiniu')['snapshotDomain'];
            $hubName = config('qiniu')['hubName'];
            $hlsDomain = config('qiniu')['hlsDomain'];
            $streamKey = "play_".$id;
            $playInfo['m3u8']    = "http://$hlsDomain/$hubName/$streamKey.m3u8";//原画
            $playInfo["m3u8_hd"] = "http://$hlsDomain/$hubName/$streamKey@720p.m3u8";//高清
            $playInfo["m3u8_sd"] = "http://$hlsDomain/$hubName/$streamKey@480p.m3u8";//标清
            $playInfo['img']     = "http://$snapshotDomain/$hubName/$streamKey.jpg";
            cache('playUrlCache'.$id,$playInfo,60);
            return $playInfo;
        }
    }

}